### ISSUE TITLE
Não gostei do projeto

### ISSUE THREAD

**Issue by exodojaffar** [erikgaborim/BMI-Calculator#1]

**Comment by erikgaborim** [comment]
Olá, meu caro amigo. Como vai?

Muito bom saber a sua opinião, contudo, devido à falta de argumentos apresentados para fundamentá-la, não posso fazer nada para melhorar o projeto.

Se você puder informar os pontos que julgou negativos na aplicação/ideia para que eu possa trabalhar para melhorá-los, agradecerei imensamente. Senão, acredito que o comentário tenha sido inadequado e peço para que você use mais a sua racionalidade antes de publicar algo.

Boa noite, qualquer coisa estou à disposição.

**Comment by exodojaffar** [comment]
O ponto que posso fundamentar para não gostar do projeto seria:
- A sua existência.

A existência do projeto realmente é um ponto que considero com muito peso e muito importante para desgostar dele, **peço que delete o repositório imediatamente!!**

Atenciosamente, seu caro amigo.

**Comment by erikgaborim** [comment]
Compreensível.

Infelizmente por motivos de **não entender qual é o problema existente na essência do projeto**, não acatarei a sugestão proposta. De qualquer forma, obrigado por comunicá-la.

Tenha uma boa noite. 

Atenciosamente, seu caro amigo.
